language: python
sudo: false
deploy:
  provider: pypi
  user: justanr
  distributions: sdist bdist_wheel
  on:
    tags: true
    repo: flaskbb/flask-debugtoolbar-warnings
    python: '3.6'
    branch: master
  password:
    secure: aRFCvmEFRx4j1m6R/vnJCI2knASlsmV8bUfkB7dwo18P2Xqzeg28k/zq73szzYTCnALZnEud3YsxaVbHlyahFVFCu90f3AIvIYwZbpqf13CKxSyMGNLnNAFCoOoigPipHHL534fAcl0ztyYDephlJNrMPU8vz162hIkof8yrcK2NSTUcQTsBZ3UJjcEoBSe6BYAGtL5Pqw6vovwiALdqug40J5JgZsWY+pfTO/yHa+LXr4nEmnWT4CfNQP6lBY/Ps+g8LvO6b6/DWLNXoYriatawsXn0Kr5ISxmYn/c47H1rLRpRkcgC63bprCEMvAR1jb4aZyJNCn5lXDjjt/dtPWyc0TL4bGByPkg6JLtrpSEQv328gzVd95vt/inaNaJ6lYT/O/AiQYnMBlLl/ydXYIA4ppWeP4NCi5hPaeFkq0JERpwJlXAjMPeiykMYGbAsLu9+5MaYnB3rObuwphkjD+CqJ0vxXnW/zYuDJbdmwolM4P/zc1jxDq2RtMBYGcOPOrxtM+AOtuygfzDJ0UK/u5jqrTQXs59ilSYMcJgLjQ2c0/LLQCV3cHZlaavEuAUPzz2OcVSZfJdtY1R6wFiEgmXmw6ko7YyJMoTN31dZ4H9nDgpfLm80cxJvVpSd46kITbZSAY/EdrBKsGPWB02XQKo/R5bGvXtqPlW1mhVSzIs=
