language: python
sudo: false
deploy:
  provider: pypi
  user: justanr
  distributions: sdist bdist_wheel
  on:
    tags: true
    repo: flaskbb/flask-debugtoolbar-warnings
    python: '3.6'
    branch: master
